version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"

  spark:
    image: apache/spark:3.4.1
    container_name: spark
    working_dir: /tmp
    volumes:
      - ./ingestion-service/ingest.py:/app/scripts/ingest.py
    environment:
      - SPARK_HOME=/opt/spark
    ports:
      - "10000:10000"  # thrift-server JDBC
    depends_on:
      - minio
    command: >
      bash -c "/opt/spark/sbin/start-thriftserver.sh --master local[*] && tail -f /dev/null"

  superset:
    build:
      context: .
      dockerfile: docker/superset.Dockerfile
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: "superset-secret"
    ports:
      - "8088:8088"
    depends_on:
      - spark

volumes:
  minio_data:
